### ISSUE TITLE
提示无法获取会话ID

### ISSUE THREAD

**Issue by wzq10314** [erzaozi/sunoai-plugin#1]
[MiaoYz][18:15:49.488][ERRO] Error: 无法获取会话ID
    at SunoAI.init (file:///root/TRSS_AllBot/Miao-Yunzai/plugins/sunoai-plugin/components/Core.js:82:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateMusic (file:///root/TRSS_AllBot/Miao-Yunzai/plugins/sunoai-plugin/apps/generateSongs.js:246:9)
    at async GenerateSongs.input (file:///root/TRSS_AllBot/Miao-Yunzai/plugins/sunoai-plugin/apps/generateSongs.js:230:17)
    at async PluginsLoader.deal (file:///root/TRSS_AllBot/Miao-Yunzai/lib/plugins/loader.js:268:41)
[MiaoYz][18:15:49.488][ERRO] Error: 无法获取会话ID
    at SunoAI.init (file:///root/TRSS_AllBot/Miao-Yunzai/plugins/sunoai-plugin/components/Core.js:82:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateMusic (file:///root/TRSS_AllBot/Miao-Yunzai/plugins/sunoai-plugin/apps/generateSongs.js:246:9)
    at async GenerateSongs.input (file:///root/TRSS_AllBot/Miao-Yunzai/plugins/sunoai-plugin/apps/generateSongs.js:230:17)
    at async PluginsLoader.deal (file:///root/TRSS_AllBot/Miao-Yunzai/lib/plugins/loader.js:268:41)
[MiaoYz][18:15:49.698][INFO] succeed to send: [Group(459345053)] 生成失败，请检查控制台输出再
试

**Comment by CikeyQi** [comment]
已修复
