### ISSUE TITLE
无法获取会话id

### ISSUE THREAD

**Issue by SaltyFishAB** [erzaozi/sunoai-plugin#5]
[MiaoYz][18:10:26.540][ERRO] Error: 无法获取会话ID
    at SunoAI.init (file:///home/user/Miao-Yunzai/plugins/sunoai-plugin/components/Core.js:86:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateMusic (file:///home/user/Miao-Yunzai/plugins/sunoai-plugin/apps/generateSongs.js:246:9)
    at async GenerateSongs.input (file:///home/user/Miao-Yunzai/plugins/sunoai-plugin/apps/generateSongs.js:156:17)
    at async PluginsLoader.deal (file:///home/user/Miao-Yunzai/lib/plugins/loader.js:269:41)

**Comment by CikeyQi** [comment]
你的 Cookie 错误或者已失效
